#!/usr/bin/env php
<?php
include __DIR__ . '/bootstrap.php';
if (@ob_get_status()) @ob_end_clean();
// comand list
$commands = [];
/**@var \wulaphp\artisan\ArtisanCommand $cmd */
foreach (apply_filter('artisan\getCommands', []) as $key => $cmd) {
    if (is_numeric($key)) {
        $commands[ $cmd->cmd() ] = $cmd;
    } else {
        $commands[ $key ] = $cmd;
    }
}
ksort($commands);

set_time_limit(0);
$cmd = isset($argv[1]) ? $argv[1] : 'help';
if ($cmd == '-v') {
    $color = new \wulaphp\artisan\Colors();
    echo $color->str('wulaphp', 'green'), ' version ', $color->str(WULA_VERSION, 'yellow'), ' ', WULA_RELEASE, "\n";
    exit(0);
} else if ($cmd == 'help' || $cmd == '--help' || $cmd == '-h') {
    $cmdi = new \wulaphp\artisan\ArtisanHelpCommand();
    exit($cmdi->run());
} else if (!isset($commands[ $cmd ])) {
    $script = APPROOT . $cmd;
    if (is_file($script)) {
        $exit = include $script;
        exit($exit === 1 ? 0 : $exit);
    }
    $cmdi = new \wulaphp\artisan\ArtisanHelpCommand();
    if ($cmd[0] == '-') {
        $cmdi->help("Unknown Option: " . $cmd);
    } else {
        $cmdi->help("Unknown Command: " . $cmd);
    }
} else {
    exit($commands[ $cmd ]->run());
}
// end of artisan